name: Node.js Package

on:
  push:
    branches:
      - main
      
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-uri: https://npm.pkg.github.com/
          scope: '@shovon'
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
          TOKEN: ${{secrets.TOKEN}}
          OWNER: ${{secrets.OWNER}}
      - run: echo ${{secrets.TOKEN}} && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
          TOKEN: ${{secrets.TOKEN}}
          OWNER: ${{secrets.OWNER}}
